import { readdir, writeFile } from "node:fs/promises";

const wasmModules = (await readdir("dist"))
  .filter((name) => name.endsWith(".wasm"))
  .sort()
  .map((name) => `    (name = "./${name}", wasm = embed "dist/${name}"),`)
  .join("\n");

if (!wasmModules) {
  throw new Error("dist/ has no .wasm modules; wrangler must emit jSquash codecs");
}

const capnp = `# Generated by scripts/write-workerd-config.ts. Do not edit by hand.
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "main", worker = .mainWorker),
    (name = "internet",
      network = (
        allow = ["public"],
        tlsOptions = (trustBrowserCas = true)
      )
    ),
  ],
  sockets = [
    (name = "http", address = "*:8080", http = (), service = "main"),
  ],
);

const mainWorker :Workerd.Worker = (
  modules = [
    (name = "index.js", esModule = embed "dist/index.js"),
${wasmModules}
  ],
  compatibilityDate = "2026-07-02",
  compatibilityFlags = ["nodejs_compat"],
  globalOutbound = "internet",
  bindings = [
    (name = "POLARION_BASE_URL", fromEnvironment = "POLARION_BASE_URL"),
    (name = "POLARION_GUIDELINES", fromEnvironment = "POLARION_GUIDELINES"),
    (name = "REST_PAGE_SIZE", fromEnvironment = "REST_PAGE_SIZE"),
    (name = "FETCH_CONCURRENCY_COUNT", fromEnvironment = "FETCH_CONCURRENCY_COUNT"),
    (name = "READ_ATTACHMENT_INLINE_RESULT_MAX_BYTES", fromEnvironment = "READ_ATTACHMENT_INLINE_RESULT_MAX_BYTES"),
    (name = "LOADER", workerLoader = ()),
  ],
);
`;

await writeFile("config.capnp", capnp);
