const DOCUMENT_OPERATION_IDS = [
  "branchDocument",
  "copyDocument",
  "getAvailableEnumOptionsForDocument",
  "getAvailableEnumOptionsForDocumentType",
  "getCurrentEnumerationOptionsForDocument",
  "getDocument",
  "getDocumentAttachment",
  "getDocumentAttachments",
  "getDocumentComment",
  "getDocumentComments",
  "getDocumentPart",
  "getDocumentParts",
  "getDocuments",
  "getSpaceDocuments",
  "mergeDocumentFromMaster",
  "mergeDocumentToMaster",
  "moveDocumentParts",
  "patchDocument",
  "patchDocumentComment",
  "postDocumentComments",
  "postDocumentParts",
  "postDocuments",
] as const;

const METADATA_OPERATION_IDS = [
  "getGlobalCustomFields",
  "getGlobalEnumeration",
  "getGlobalEnumerations",
  "getGlobalFieldsMetadata",
  "getMetadata",
  "getProjectCustomFields",
  "getProjectEnumeration",
  "getProjectEnumerations",
  "getProjectFieldsMetadata",
] as const;

const PLAN_OPERATION_IDS = [
  "deletePlan",
  "deletePlanRelationship",
  "deletePlans",
  "getPlan",
  "getPlanRelationship",
  "getPlans",
  "patchPlan",
  "patchPlanRelationships",
  "postPlanRelationships",
  "postPlans",
] as const;

const JOB_OPERATION_IDS = ["executeJob", "getJob", "getJobs"] as const;

const PROJECT_OPERATION_IDS = [
  "closeCollection",
  "deleteCollection",
  "deleteCollections",
  "deleteCollectionsRelationship",
  "deletePage",
  "deletePageAttachment",
  "deletePageRelationships",
  "getCollection",
  "getCollections",
  "getCollectionsRelationship",
  "getPage",
  "getPageAttachment",
  "getPageAttachments",
  "getPageComment",
  "getPageComments",
  "getPageRelationships",
  "getPages",
  "getProject",
  "getProjects",
  "getProjectTestParameterDefinition",
  "getProjectTestParameterDefinitions",
  "getSpacePages",
  "patchCollections",
  "patchCollectionsRelationships",
  "patchPageComment",
  "patchPageRelationships",
  "patchRichPage",
  "postCollections",
  "postCollectionsRelationships",
  "postPageComments",
  "postPageRelationships",
  "postPages",
  "reopenCollection",
  "reuseCollection",
] as const;

const TEST_RUN_OPERATION_IDS = [
  "deleteTestRecord",
  "deleteTestRecordAttachment",
  "deleteTestRecordAttachments",
  "deleteTestRecordTestParameter",
  "deleteTestRun",
  "deleteTestRunAttachment",
  "deleteTestRunAttachments",
  "deleteTestRuns",
  "deleteTestRunTestParameter",
  "deleteTestRunTestParameterDefinition",
  "deleteTestRunTestParameters",
  "deleteTestStepResultAttachment",
  "deleteTestStepResultAttachments",
  "getTestRecord",
  "getTestRecordAttachment",
  "getTestRecordAttachments",
  "getTestRecords",
  "getTestRecordTestParameter",
  "getTestRecordTestParameters",
  "getTestRun",
  "getTestRunAttachment",
  "getTestRunAttachments",
  "getTestRunComment",
  "getTestRunComments",
  "getTestRuns",
  "getTestRunTestParameter",
  "getTestRunTestParameterDefinition",
  "getTestRunTestParameterDefinitions",
  "getTestRunTestParameters",
  "getTestStepResult",
  "getTestStepResultAttachment",
  "getTestStepResultAttachments",
  "getTestStepResults",
  "getWorkflowActionsForTestRun",
  "patchTestRecord",
  "patchTestRecords",
  "patchTestRun",
  "patchTestRunComment",
  "patchTestRunComments",
  "patchTestRuns",
  "patchTestStepResult",
  "patchTestStepResults",
  "postTestRecords",
  "postTestRecordTestParameters",
  "postTestRunComments",
  "postTestRunParameterDefinitions",
  "postTestRuns",
  "postTestRunTestParameters",
  "postTestStepResults",
] as const;

const WORK_ITEM_OPERATION_IDS = [
  "deleteApproval",
  "deleteApprovals",
  "deleteExternallyLinkedWorkItem",
  "deleteExternallyLinkedWorkItems",
  "deleteLinkedWorkItem",
  "deleteLinkedWorkItems",
  "deleteOslcResources",
  "deleteTestStep",
  "deleteTestSteps",
  "deleteWorkItemAttachment",
  "deleteWorkItems",
  "deleteWorkItemsRelationship",
  "deleteWorkRecord",
  "deleteWorkRecords",
  "getAvailableEnumOptionsForWorkItem",
  "getAvailableEnumOptionsForWorkItemType",
  "getBacklinkedWorkItems",
  "getComment",
  "getComments",
  "getCurrentEnumOptionsForWorkItem",
  "getExternallyLinkedWorkItem",
  "getExternallyLinkedWorkItems",
  "getFeatureSelection",
  "getFeatureSelections",
  "getLinkedWorkItem",
  "getLinkedWorkItems",
  "getOslcResources",
  "getTestStep",
  "getTestSteps",
  "getWorkflowActionsForWorkItem",
  "getWorkItem",
  "getWorkItemApproval",
  "getWorkItemApprovals",
  "getWorkItemAttachment",
  "getWorkItemAttachments",
  "getWorkItems",
  "getWorkItemsRelationships",
  "getWorkItemTestParameterDefinition",
  "getWorkItemTestParameterDefinitions",
  "getWorkRecord",
  "getWorkRecords",
  "moveFromDocument",
  "moveToDocument",
  "patchComment",
  "patchLinkedWorkItem",
  "patchTestStep",
  "patchTestSteps",
  "patchWorkItem",
  "patchWorkItemApproval",
  "patchWorkItemApprovals",
  "patchWorkItemRelationships",
  "patchWorkItems",
  "postBacklinkedWorkItems",
  "postComments",
  "postExternallyLinkedWorkItems",
  "postLinkedWorkItems",
  "postOslcResources",
  "postTestSteps",
  "postWorkItemApprovals",
  "postWorkItemRelationships",
  "postWorkItems",
  "postWorkRecords",
] as const;

export const ALLOWED_OPERATION_IDS = new Set<string>([
  ...DOCUMENT_OPERATION_IDS,
  ...METADATA_OPERATION_IDS,
  ...PLAN_OPERATION_IDS,
  ...JOB_OPERATION_IDS,
  ...PROJECT_OPERATION_IDS,
  ...TEST_RUN_OPERATION_IDS,
  ...WORK_ITEM_OPERATION_IDS,
]);
